patient_new:
    pattern:  /person/new
    defaults: { _controller: TeclliurePatientBundle:Default:new }

patient_update:
    pattern:  /person/update/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:update, id: null }

patient_delete:
    pattern:  /person/{id}/delete
    defaults: { _controller: TeclliurePatientBundle:Default:delete }

patient_show:
    pattern:  /person/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:show }

patient_content:
    pattern:  /reloadPatientContent/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:reloadPatientContent }

questionary_patient_new:
    pattern:  /person/{id}/selectQuestionary
    defaults: { _controller: TeclliurePatientBundle:Default:selectQuestionary }

questionary_patient_create:
    pattern:  /patientQuestionary/person/{id}/questionary/{questionaryId}/patientQuestionaryId/{patientQuestionaryId}
    defaults: { _controller: TeclliurePatientBundle:Default:createQuestionary, patientQuestionaryId: null }

questionary_patient_delete:
    pattern:  /patientQuestionary/delete/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:deletePatientQuestionary }

questionary_patient_validation:
    pattern:  /patientQuestionary/validations/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:validationPatientQuestionary }

questionary_patient_results:
    pattern:  /patientQuestionary/results/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:resultsPatientQuestionary }

patient_report:
    pattern:  /patientReport/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:patientReport }