patient_new:
    pattern:  /person/new
    defaults: { _controller: TeclliurePatientBundle:Default:new }

patient_update:
    pattern:  /person/update/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:update, id: null }

patient_delete:
    pattern:  /person/{id}/delete
    defaults: { _controller: TeclliurePatientBundle:Default:delete }

patient_show:
    pattern:  /person/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:show }

patient_content:
    pattern:  /reloadPatientContent/{id}
    defaults: { _controller: TeclliurePatientBundle:Default:reloadPatientContent }

questionary_patient_new:
    pattern:  /person/{id}/selectQuestionary
    defaults: { _controller: TeclliurePatientBundle:Default:selectQuestionary }

questionary_patient_create:
    pattern:  /person/{id}/selectQuestionary/{questionaryId}
    defaults: { _controller: TeclliurePatientBundle:Default:createQuestionary }