parameters:
#    teclliure_user.example.class: Teclliure\UserBundle\Example

services:
    sonata.teclliure.admin.patient:
        class: Teclliure\PatientBundle\Admin\PatientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: 'Patients', label: Patients }
        arguments:
            - null
            - Teclliure\PatientBundle\Entity\Patient
            - TeclliureUserBundle:Admin

    teclliure_patient_questionary_validation_type:
        class:        Teclliure\QuestionBundle\Form\PatientQuestionaryValidationType
        arguments:
            em: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: teclliure_questionbundle_patientquestionary_validationtype }