login:
    pattern:  /login
    defaults: { _controller: TeclliureUserBundle:Default:login }

register:
    pattern:  /register
    defaults: { _controller: TeclliureUserBundle:Default:register }

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout