parameters:
#    teclliure_user.example.class: Teclliure\UserBundle\Example

services:
#    teclliure_user.example:
#        class: %teclliure_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
