language: php

php:
#  - 5.3.3
  - 5.3
#  - 5.4

before_script: composer install

# Let phpunit generate the code coverage report in the clover format
script: phpunit --coverage-clover "clover" -c app

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php
