teclliure_category:
    resource: "@TeclliureCategoryBundle/Controller/"
    type:     annotation
    prefix:   /

teclliure_patient:
    resource: "@TeclliurePatientBundle/Controller/"
    type:     annotation
    prefix:   /

teclliure_user:
    resource: "@TeclliureUserBundle/Resources/config/routing.yml"
    prefix:   /

teclliure_question:
    resource: "@TeclliureQuestionBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
