home:
    pattern:  /
    defaults: { _controller: TeclliureDashboardBundle:Default:index }

teclliure_dashboard:
    resource: "@TeclliureDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

teclliure_category:
    resource: "@TeclliureCategoryBundle/Controller/"
    type:     annotation
    prefix:   /category

teclliure_patient:
    resource: "@TeclliurePatientBundle/Controller/"
    type:     annotation
    prefix:   /patient

teclliure_user:
    resource: "@TeclliureUserBundle/Resources/config/routing.yml"
    prefix:   /user

teclliure_question:
    resource: "@TeclliureQuestionBundle/Resources/config/routing.yml"
    prefix:   /question

sonata:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

TeclliureQuestionBundle_questionary:
    resource: "@TeclliureQuestionBundle/Resources/config/routing/questionary.yml"
    prefix:   /admin/questionary

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
