questionary:
    pattern:  /
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:index" }

questionary_show:
    pattern:  /{id}/show
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:show" }

questionary_new:
    pattern:  /new
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:new" }

questionary_create:
    pattern:  /create
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:create" }
    requirements: { _method: post }

questionary_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:edit" }

questionary_update:
    pattern:  /{id}/update
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:update" }
    requirements: { _method: post }

questionary_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:delete" }

question_save:
    pattern:  /saveQuestion/{id}
    defaults:
        _controller: "TeclliureQuestionBundle:Questionary:saveQuestion"
        requirements:
            _method:  POST

question_sort:
    pattern:  /sortQuestion/{questionId}/{sortOrder}
    defaults:
        _controller: "TeclliureQuestionBundle:Questionary:sortQuestion"
        requirements:
            _method:  GET

question_delete:
    pattern:  /deleteQuestion/{questionId}
    defaults:
        _controller: "TeclliureQuestionBundle:Questionary:deleteQuestion"
        requirements:
            _method:  GET

answer_form_show:
    pattern:  /formAnswer/{questionId}
    defaults:
        _controller: "TeclliureQuestionBundle:Questionary:formAnswer"
        requirements:
            _method:  GET

answer_save:
    pattern:  /saveAnswer/{questionId}
    defaults:
        _controller: "TeclliureQuestionBundle:Questionary:saveAnswer"
        requirements:
            _method:  POST

answer_delete:
    pattern:  /deleteAnswer/{answerId}
    defaults:
        _controller: "TeclliureQuestionBundle:Questionary:deleteAnswer"
        requirements:
            _method:  GET

answer_sort:
    pattern:  /sortAnswer/{answerId}/{sortOrder}
    defaults:
        _controller: "TeclliureQuestionBundle:Questionary:sortAnswer"
        requirements:
            _method:  GET