questionary:
    pattern:  /
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:index" }

questionary_show:
    pattern:  /{id}/show
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:show" }

questionary_new:
    pattern:  /new
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:new" }

questionary_create:
    pattern:  /create
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:create" }
    requirements: { _method: post }

questionary_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:edit" }

questionary_update:
    pattern:  /{id}/update
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:update" }
    requirements: { _method: post }

questionary_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TeclliureQuestionBundle:Questionary:delete" }

question_save:
    pattern:  /saveQuestion/{id}/{questionId}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:saveQuestion"
        questionId: null
        requirements:
            _method:  POST

question_edit:
    pattern:  /editQuestion/{questionId}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:editQuestion"
        requirements:
            _method:  GET

question_sort:
    pattern:  /sortQuestion/{questionId}/{sortOrder}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:sortQuestion"
        requirements:
            _method:  GET

question_delete:
    pattern:  /deleteQuestion/{questionId}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:deleteQuestion"
        requirements:
            _method:  GET

answer_form_show:
    pattern:  /formAnswer/{questionId}/{answerId}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:formAnswer"
        answerId: null
        requirements:
            _method:  GET

answer_save:
    pattern:  /saveAnswer/{questionId}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:saveAnswer"
        requirements:
            _method:  POST

answer_delete:
    pattern:  /deleteAnswer/{answerId}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:deleteAnswer"
        requirements:
            _method:  GET

answer_sort:
    pattern:  /sortAnswer/{answerId}/{sortOrder}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:sortAnswer"
        requirements:
            _method:  GET

            question_save:
                pattern:  /saveQuestion/{id}
                defaults:
                    _controller: "TeclliureQuestionBundle:Question:saveQuestion"
                    requirements:
                        _method:  POST
validation_edit:
    pattern:  /editValidation/{validationId}
    defaults:
        _controller: "TeclliureQuestionBundle:Validation:editValidation"
        requirements:
            _method:  GET

validation_save:
    pattern:  /saveValidation/{id}/{validationId}
    defaults:
        _controller: "TeclliureQuestionBundle:Validation:saveValidation"
        validationId: null
        requirements:
            _method:  POST


validation_sort:
    pattern:  /sortValidation/{validationId}/{sortOrder}
    defaults:
        _controller: "TeclliureQuestionBundle:Validation:sortValidation"
        requirements:
            _method:  GET

validation_delete:
    pattern:  /deleteValidation/{validationId}
    defaults:
        _controller: "TeclliureQuestionBundle:Validation:deleteValidation"
        requirements:
            _method:  GET

rule_form_show:
    pattern:  /formRule/{validationId}/{ruleId}
    defaults:
        _controller: "TeclliureQuestionBundle:Validation:formRule"
        ruleId: null
        requirements:
            _method:  GET

rule_save:
    pattern:  /saveRule/{validationId}/{ruleId}
    defaults:
        _controller: "TeclliureQuestionBundle:Validation:saveRule"
        ruleId: null
        requirements:
            _method:  POST

rule_delete:
    pattern:  /deleteRule/{ruleId}
    defaults:
        _controller: "TeclliureQuestionBundle:Validation:deleteRule"
        requirements:
            _method:  GET

validation_questions:
    pattern:  /validationQuestions/{id}
    defaults:
        _controller: "TeclliureQuestionBundle:Validation:saveValidationQuestions"

validation_questions_number:
    pattern:  /validation/getQuestionsNumber/{id}
    defaults:
        _controller: "TeclliureQuestionBundle:Validation:getValidationQuestionsNumber"

answer_questions:
    pattern:  /answerQuestions/{id}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:saveAnswerQuestions"

answer_questions_number:
    pattern:  /answer/getQuestionsNumber/{id}
    defaults:
        _controller: "TeclliureQuestionBundle:Question:getAnswerQuestionsNumber"