parameters:
#    teclliure_user.example.class: Teclliure\UserBundle\Example

services:
    sonata.teclliure.admin.category:
        class: Teclliure\CategoryBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: 'Categories and subcategories', label: Categories }
        arguments:
            - null
            - Teclliure\CategoryBundle\Entity\Category
            - TeclliureUserBundle:Admin

    sonata.teclliure.admin.subcategory:
        class: Teclliure\CategoryBundle\Admin\SubcategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: 'Categories and subcategories', label: Subcategories }
        arguments:
            - null
            - Teclliure\CategoryBundle\Entity\Subcategory
            - TeclliureUserBundle:Admin
